### PR TITLE
Add ability to use a checkstyle-like suppressions file

### PR DESCRIPTION
**Pull request by mlbileschi**
Add ability to use a checkstyle-like suppressions file to allow for more fine-grained control over when to run rules.

Use case: adding new rules to large repo. We want to ratchet the coverage by requiring all new projects to follow the rules, but we don't require cleanup for old projects right away.

The suppressions files look like this

```
<suppressions>
  <suppress files="regex1" checks="regex2"/>
</suppressions>
```

New help output:

```
$ java -cp /Users/mbileschi/workspace/videoscalastyle/target/scala-2.10/scalastyle-assembly-0.8.0-SNAPSHOT.jar org.scalastyle.Main --help
scalastyle 0.8.0-SNAPSHOT
Usage: scalastyle [options] <source directory>
 -c, --config FILE               configuration file (required)
 -v, --verbose true|false        verbose output
 -q, --quiet true|false          be quiet
     --xmlOutput FILE            write checkstyle format output to this file
     --xmlEncoding STRING        encoding to use for the xml file
     --inputEncoding STRING      encoding for the source files
 -w, --warnings true|false       fail if there are warnings
 -e, --externalJar FILE          jar containing custom rules
 -x, --excludedFiles STRING      regular expressions to exclude file paths (delimited by semicolons).
                                 Cannot be used in conjunction with suppressions files.
 -s, --suppressionsFile STRING   path to checkstyle-like suppressions xml file. For example, the
                                 following config would exclude scalastyle checks with class names
                                 containing regex2 from being run on files containing regex1. More than
                                 one suppress tag is allowed.
                                   <suppressions>
                                     <suppress files="regex1" checks="regex2"/>
                                   </suppressions>
```

It looks like a large change, but that's mostly because I renamed `CheckerTest` to `CheckerTestHelper` so I could add a file that tested the file `Checker.scala`, and this accounts for about 200 lines of the diff.

### CODE REVIEW

**Comment by mlbileschi** [comment]
I will rebase before merging, but I'd like to keep the history through the review process.

**Comment by matthewfarwell** [comment]
This is an interesting change, and I'd like to discuss it more, but I can't accept a pull request of this size and complexity. Can we do this without the name change? You can always move the necessary function to an Suppression object and the have a SuppressionTest or something like that.

**Comment by mlbileschi** [comment]
@matthewfarwell sure! I've opened https://github.com/scalastyle/scalastyle/pull/171 which does the name change, and adds the test CheckerTest (the reason for the name change in the first place). In the meantime, I've opened https://github.com/mlbileschi/scalastyle/pull/1 so you can see the diff minus the name change.

Thanks!

**Comment by matthewfarwell** [comment]
Closed due to lack of activity. If you still want this, can you reopen a new PR based on the latest master. Thanks.

**Comment by LiShuMing** [comment]
This feature seems very useful because I need to exclude some files.

BTW, Is there other way to exclude files in  `Scala stylecheck` ?

**Pull request closed without merging**
