### PR TITLE
[Maintenance] Fix triple-quotes with stripMargin and semi-colons.

### PR DESCRIPTION
**Pull request by aa8y**
This code uses stripMargin to with triple-quotes to make the code more readable. Also tries to make its usage consistent. Also removes semi-colons where not needed. I tried to make only there specific changes and no other. Let me know if the code deviates from this and I will revert those changes. No new tests need to be added but all the tests pass.

### CODE REVIEW

**Comment by matthewfarwell** [comment]
Some of these changes have been made in other commits (such as removing ;). I'm not bothered about the lack of consistency when using stripMargin. If anything, I would suggest removing stripMargin.

I'm happy to accept contributions, but I can't accept this one.

**Comment by aa8y** [comment]
Why would you not want any `stripMargin`. Its intended use is exactly for what my commit does. Also, it makes the code a lot more readable and consistent.

**Comment by aa8y** [comment]
@matthewfarwell I saw I had this PR from a few months ago. So wanted to bump it. You said you would like to remove `stripMargin` altogether. I don't see why though.

**Comment by matthewfarwell** [comment]
I prefer to use straight triple quotes, because I think it looks nicer and I can cut and paste directly to files. Sorry, can't accept this PR.

**Pull request closed without merging**
