### PR TITLE
Switch to scalariform 0.1.7

### LINKED ISSUE #156: sbt 0.13.9  scala 2.10.5 not backward compatibility
If class contains `<` the scalastyle parser failed with error:
```
Expected token RBRACKET but got Token(XML_START_OPEN,<,63,<)
```

Infected file:
```
case class EnumWrapper[E <: Enum[E]](a: E
```

Maybe it affects parser, see:
https://github.com/scala/scala/pull/4185

Environment:
sbt 0.13.9
scala 2.10.5 (used by sbt 0.13.9)

### PR DESCRIPTION
**Pull request by kciesielski**
- This fixes #156

### CODE REVIEW

**Comment by JoshRosen** [comment]
Friendly bump. @dragos, any chance that you could take a look at this? We have some repositories where Scalastyle is currently disabled due to this Scalariform issue, so it would be great to have new `scalastyle` and `scalastyle-sbt` packages which incorporate this fix. We can always add an explicit dependency on Scalariform, but it would be easier to just use a newer release.

**Comment by ahirreddy** [comment]
I used this snippet to fix it for the time being:
```scala
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.7.0" excludeAll(
  ExclusionRule(organization = "com.danieltrinh")))
libraryDependencies += "org.scalariform" %% "scalariform" % "0.1.7"
```

**Comment by dragos** [comment]
@matthewfarwell Should we release a scalastyle update? There are 2-3 new rules, and this fix.

**Comment by JoshRosen** [comment]
+1 on releasing a new version.

**Comment by vanzin** [comment]
Yes, a new version would be mostly welcome.

**Comment by lunaryorn** [comment]
Indeed, we'd welcome a new release, too.

**Comment by JoshRosen** [comment]
@matthewfarwell, gentle bump. The Spark team would greatly appreciate a new Scalastyle release, as would a number of projects.

**Comment by gregsymons** [comment]
Is there something blocking this release? scalastyle-sbt-plugin has been broken on the latest stable sbt for two months now (unless you use @ahirreddy's hack). I'll gladly pitch in and help to get this release out if there's something specific blocking it.

**Comment by vanzin** [comment]
Hi @matthewfarwell , is there any chance we can get a new release with the recent changes?

**Comment by JoshRosen** [comment]
:tada: Yay! :tada: Thanks for releasing [v0.8.0](https://github.com/scalastyle/scalastyle/releases/tag/v0.8.0), @matthewfarwell!

**Comment by lunaryorn** [comment]
A big thanks from me, too 👍🎆

**Pull request merged**
