### PR TITLE
Fix import checker missing wrongly sorted packages.

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by vanzin** [comment]
Ping?

**Comment by vanzin** [comment]
Ping again?

**Comment by matthewfarwell** [comment]
Cool. Thanks!

**Comment by vanzin** [comment]
@matthewfarwell thanks! Any plans to release a 0.8.x version to include recent fixes?

**Comment by vanzin** [comment]
Hi @matthewfarwell, any chance of a maintenance release? Thanks!

**Pull request merged**
