### PR TITLE
implement regex rules where performed line by line.

### PR DESCRIPTION
**Pull request by anvie**
Sometimes I need to match regex line by line.

### CODE REVIEW

**Comment by matthewfarwell** [comment]
Hi.

Can you give me a use case for this? Also, what does this give you that you don't get with the normal regex checker?

Also, would it a better idea to have this as an option to the normal regex checker, rather than it's own checker?

**Comment by anvie** [comment]
Hi @matthewfarwell ,

The use case can be found in the test, for example I need to track line that matching `println` like this: 

https://github.com/scalastyle/scalastyle/pull/165/files#diff-3966d6b5b3dc64d55ceb337fda261970R35

but not `println` where started with `//` (commented out) like this:

https://github.com/scalastyle/scalastyle/pull/165/files#diff-3966d6b5b3dc64d55ceb337fda261970R36

Using existing RegexChecker I actually can use regex syntax with modifier `(?m)`, but unfortunately the reporter catch wrong line number, for example given this test: https://github.com/scalastyle/scalastyle/pull/165/files#diff-3966d6b5b3dc64d55ceb337fda261970R32
RegexChecker reported line 34 instead of 35, where 34 is the location of method declaration not the `println`.

**Comment by matthewfarwell** [comment]
Ok, the use case is fine. I'd still like this to be an option to the existing checker, rather than a separate checker. If you add the option "line" which is a boolean which if true, uses your method, otherwise the existing.

I can do this, but if you want to, go ahead. I'm going to release very soon.

**Comment by anvie** [comment]
Thank for review. Ok, let me try.

**Comment by anvie** [comment]
hi @matthewfarwell I just made an update, please kindly check

**Comment by matthewfarwell** [comment]
I'll check this evening, but LGTM. Thanks.

**Comment by matthewfarwell** [comment]
Thanks!

**Pull request merged**
