### PR TITLE
Add option to NonASCIICharacterChecker to allow international characters in string literals

### LINKED ISSUE #283: Add option to NonASCIICharacterChecker to allow international characters in string literals
When writing in languages other than English, non-ASCII characters in string literals are usually needed:

```scala
val greeting = "olá"
```

Add an option to `NonASCIICharacterChecker` to allow international characters in string literals (but not identifiers). A regex like `[\p{Alnum}\p{Punct}\p{Sc}\p{Space}]+` should probably be sufficient for most cases.

### PR DESCRIPTION
**Pull request by marconilanna**
Fixes #283

### CODE REVIEW

**Comment by matthewfarwell** [comment]
Thanks for this. I will look at it this week.

**Comment by marconilanna** [comment]
@matthewfarwell i need your help here. i'm getting a

    [error] Test org.scalastyle.MessageHelperTest.testMessages failed: "non.ascii.character.disallowed.whiteListStringLiterals.description" equaled "non.ascii.character.disallowed.whiteListStringLiterals.description" checker non.ascii.character.disallowed.whiteListStringLiterals should have a (non.ascii.character.disallowed.whiteListStringLiterals.description)

error and i'm not sure why.

**Comment by matthewfarwell** [comment]
@marconilanna You need to escape the {} in the ```reference.conf```. Something like:

`
non.ascii.character.disallowed.whiteListStringLiterals.description = "White lists Unicode characters recognized by `\\p'{'Alnum'}'\\p'{'Punct'}'\\p'{'Sc'}'\\p'{'Space'}'` but not symbols like Emoji."
`

**Comment by marconilanna** [comment]
@matthewfarwell ready for code review

**Comment by matthewfarwell** [comment]
This is great. Sorry for not picking up on it before, but I think the name of the parameter could be better. How about just ```allowStringLiterals```? This conveys the same meaning, and is consistent with some of the other parameters, such as allowNullChecks.

WDYT?

**Comment by marconilanna** [comment]
sure, no problem. i was struggling to come up with a meaningful parameter name, thank you for the suggestion. do you think we should allow any unicode character in string literals or just the white listed ones?

**Comment by marconilanna** [comment]
@matthewfarwell parameter renamed

**Comment by matthewfarwell** [comment]
Great. Thanks!

**Pull request merged**
