### PR TITLE
Add scala.Any and Object to the list of "object" types

### PR DESCRIPTION
**Pull request by nrinaudo**
This addresses #281, as discussed in [gitter](https://gitter.im/scalastyle/scalastyle?at=59d759bef7299e8f53b55b56).

### CODE REVIEW

**Comment by canoztokmak** [comment]
Hey @nrinaudo,

It would be great if you add a test case for this pr as well.

**Comment by nrinaudo** [comment]
@canoztokmak happy to. The reason I haven't is because I looked, and couldn't find, an existing test for `isObject` on which to piggy-back.

Did I miss it, or is it just not there and you'd like to use the opportunity to add it?

**Comment by matthewfarwell** [comment]
I'll add the test case when I merge the PR.

Thanks.

**Comment by matthewfarwell** [comment]
Thanks!

**Pull request merged**
