### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by anilkumarmyla**
This upgrades dependent libraries to their latest versions

### CODE REVIEW

**Comment by anilkumarmyla** [comment]
@matthewfarwell

**Comment by niebloomj** [comment]
What is this waiting on?

**Comment by mwz** [comment]
@niebloomj - this project is no longer maintained, I've been trying to maintain it on a separate fork here https://github.com/beautiful-scala/scalastyle.

See https://github.com/scalastyle/scalastyle/issues/327 for more context.

**Comment by niebloomj** [comment]
I see it and started using it in my project. Are you looking for another maintainer? Thanks.

**Comment by mwz** [comment]
Yes @niebloomj, having some help would be great.

**Comment by anilkumarmyla** [comment]
scala-steward can take care of dependency upgrades ;-)

**Pull request closed without merging**
