### PR TITLE
version bumps (including Scalariform)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Review by canoztokmak — APPROVED** [review]
👍

**Comment by SethTisue** [comment]
hmm, the contributions graph at https://github.com/matthewfarwell doesn't look promising

anyone know Matthew IRL and could ask him if he could anoint additional maintainers?

**Comment by SethTisue** [comment]
@matthewfarwell are you merging PRs in this repo...?

**Comment by matthewfarwell** [comment]
Yes, I am merging PRs into this repo, I will do it later this week.

**Comment by mwz** [comment]
Could we get a new scalastyle release once this is merged? It has been ages since scalastyle was last released.

**Comment by chilang** [comment]
@matthewfarwell Can we get a new release out? I've a codebase which scalastyle (1.0.0) stackoverflow due to old scalariform bug (fixed in 0.2.7)  https://github.com/scala-ide/scalariform/pull/267

**Pull request merged**
